set shell := ["sh", "-c"]
set windows-shell := ["powershell", "-c"]

_main:
    @just --list

# run source .venv/bin/activate before running this
build:
	mojo build ui.mojo -o app -Xlinker libui.a $(pkg-config --libs gtk+-3.0 | xargs -n1 echo -Xlinker)

demo:
	mojo build demo.mojo -o demo -Xlinker libui.a $(pkg-config --libs gtk+-3.0 | xargs -n1 echo -Xlinker)

demo_raw:
	mojo build demo_raw.mojo -o demo_raw -Xlinker libui.a $(pkg-config --libs gtk+-3.0 | xargs -n1 echo -Xlinker)
